// <auto-generated />
using System;
using HOSPITAL_MANAGEMENT_SYSTEM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOSPITAL_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2026, 9, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateTime(2026, 9, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            PatientId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateTime(2026, 9, 29, 11, 3, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentDate = new DateTime(2026, 9, 29, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            PatientId = 4,
                            Status = "Cancelled"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentDate = new DateTime(2026, 9, 28, 11, 3, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentDate = new DateTime(2026, 9, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            PatientId = 6,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Department", b =>
                {
                    b.Property<int>("DepartementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartementId"));

                    b.Property<string>("DepartementLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DepartementName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartementId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartementId = 1,
                            DepartementLocation = "Cairo",
                            DepartementName = "Cardiology"
                        },
                        new
                        {
                            DepartementId = 2,
                            DepartementLocation = "Giza",
                            DepartementName = "Pediatrics"
                        },
                        new
                        {
                            DepartementId = 3,
                            DepartementLocation = "Cairo",
                            DepartementName = "Orthopedics"
                        },
                        new
                        {
                            DepartementId = 4,
                            DepartementLocation = "Giza",
                            DepartementName = "Dermatology"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DoctorFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DoctorPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DoctorSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DoctorSpecialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId");

                    b.HasIndex("DepartementId");

                    b.HasIndex("DoctorEmail")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            DepartementId = 1,
                            DoctorEmail = "ahmed.hassan@hms.com",
                            DoctorFullName = "Ahmed Hassan",
                            DoctorPhone = "01010000001",
                            DoctorSalary = 45000m,
                            DoctorSpecialization = "Cardiologist"
                        },
                        new
                        {
                            DoctorId = 2,
                            DepartementId = 1,
                            DoctorEmail = "mona.adel@hms.com",
                            DoctorFullName = "Mona Adel",
                            DoctorPhone = "01010000002",
                            DoctorSalary = 42000m,
                            DoctorSpecialization = "Cardiologist"
                        },
                        new
                        {
                            DoctorId = 3,
                            DepartementId = 2,
                            DoctorEmail = "omar.khaled@hms.com",
                            DoctorFullName = "Omar Khaled",
                            DoctorPhone = "01010000003",
                            DoctorSalary = 38000m,
                            DoctorSpecialization = "Pediatrician"
                        },
                        new
                        {
                            DoctorId = 4,
                            DepartementId = 2,
                            DoctorEmail = "nour.samir@hms.com",
                            DoctorFullName = "Nour Samir",
                            DoctorPhone = "01010000004",
                            DoctorSalary = 36000m,
                            DoctorSpecialization = "Pediatrician"
                        },
                        new
                        {
                            DoctorId = 5,
                            DepartementId = 3,
                            DoctorEmail = "karim.tarek@hms.com",
                            DoctorFullName = "Karim Tarek",
                            DoctorPhone = "01010000005",
                            DoctorSalary = 50000m,
                            DoctorSpecialization = "Orthopedic Surgeon"
                        },
                        new
                        {
                            DoctorId = 6,
                            DepartementId = 3,
                            DoctorEmail = "salma.youssef@hms.com",
                            DoctorFullName = "Salma Youssef",
                            DoctorPhone = "01010000006",
                            DoctorSalary = 41000m,
                            DoctorSpecialization = "Orthopedic Specialist"
                        },
                        new
                        {
                            DoctorId = 7,
                            DepartementId = 4,
                            DoctorEmail = "youssef.emad@hms.com",
                            DoctorFullName = "Youssef Emad",
                            DoctorPhone = "01010000007",
                            DoctorSalary = 39000m,
                            DoctorSpecialization = "Dermatologist"
                        },
                        new
                        {
                            DoctorId = 8,
                            DepartementId = 4,
                            DoctorEmail = "laila.mostafa@hms.com",
                            DoctorFullName = "Laila Mostafa",
                            DoctorPhone = "01010000008",
                            DoctorSalary = 37000m,
                            DoctorSpecialization = "Dermatologist"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalRecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MedicalRecordId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            MedicalRecordId = 1,
                            AppointmentId = 3,
                            Description = "5mg once daily Follow",
                            Diagnosis = "Hypertension Amlodipine",
                            Notes = "up after two weeks."
                        },
                        new
                        {
                            MedicalRecordId = 2,
                            AppointmentId = 5,
                            Description = "Rest and fluids",
                            Diagnosis = "Acute respiratory infection",
                            Notes = "Patient advised to return if symptoms worsen."
                        },
                        new
                        {
                            MedicalRecordId = 3,
                            AppointmentId = 6,
                            Description = "Physiotherapy and rest",
                            Diagnosis = "Knee ligament injury",
                            Notes = "MRI recommended."
                        },
                        new
                        {
                            MedicalRecordId = 4,
                            AppointmentId = 2,
                            Description = "Topical moisturizer twice daily",
                            Diagnosis = "Mild eczema",
                            Notes = "Avoid known skin irritants."
                        },
                        new
                        {
                            MedicalRecordId = 5,
                            AppointmentId = 4,
                            Description = "Paracetamol as needed",
                            Diagnosis = "Migraine",
                            Notes = "Maintain regular sleep schedule."
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("PatientDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PatientGender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("patientAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            PatientDateOfBirth = new DateTime(1995, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientFullName = "Omer Ali",
                            PatientGender = "Male",
                            PatientPhone = "01120000001",
                            patientAddress = "Nasr City, Cairo"
                        },
                        new
                        {
                            PatientId = 2,
                            PatientDateOfBirth = new DateTime(1998, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientFullName = "Sara Ahmed",
                            PatientGender = "Female",
                            PatientPhone = "01120000002",
                            patientAddress = "Dokki, Giza"
                        },
                        new
                        {
                            PatientId = 3,
                            PatientDateOfBirth = new DateTime(1987, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientFullName = "Mahmoud Samir",
                            PatientGender = "Male",
                            PatientPhone = "01120000003",
                            patientAddress = "Heliopolis, Cairo"
                        },
                        new
                        {
                            PatientId = 4,
                            PatientDateOfBirth = new DateTime(2002, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientFullName = "Mariam Adel",
                            PatientGender = "Female",
                            PatientPhone = "01120000004",
                            patientAddress = "Giza"
                        },
                        new
                        {
                            PatientId = 5,
                            PatientDateOfBirth = new DateTime(1979, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientFullName = "Yassin Mohamed",
                            PatientGender = "Male",
                            PatientPhone = "01120000005",
                            patientAddress = "Maadi, Cairo"
                        },
                        new
                        {
                            PatientId = 6,
                            PatientDateOfBirth = new DateTime(1991, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientFullName = "Hana Khaled",
                            PatientGender = "Female",
                            PatientPhone = "01120000006",
                            patientAddress = "October, Giza"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Doctor", b =>
                {
                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.MedicalRecord", b =>
                {
                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("HOSPITAL_MANAGEMENT_SYSTEM.Models.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
